### ISSUE TITLE
Can it be flashed with router firmware?

### ISSUE THREAD

**Issue by zuhair68** [Gio-dot/Z-Bee-Duo#1]
Can this device be flashed with router firmware? It would be nice if it's flashed as router and connected to PI Zero and plugged anywhere in the house.

**Comment by Gio-dot** [comment]
Yes, this is the router firmware that can be used:
https://github.com/Koenkk/Z-Stack-firmware/blob/master/router/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_other_router_20210128.zip
