### ISSUE TITLE
change of subnet not connecting to wifi

### ISSUE THREAD

**Issue by mariomare22** [Gio-dot/Z-Bee-Duo#11]
Hello!
I am using a zbee duo with ESP wifi module.

I recently changed my ip class from 192.168.1.0/24 to 10.10.0.0/27 but the device is no longer connecting to the wifi nor getting an IP.

I tried to re-add the network using the fallback option but without luck.

Do you have any idea what is causing this issue?

thanks Mario

**Comment by gio-dot** [comment]
Hi, im sorry i don't know why.

**Comment by mariomare22** [comment]
all good, it was just a little slow to catch up.
