### ISSUE TITLE
Devices get disconnected

### ISSUE THREAD

**Issue by manunited10** [Gio-dot/Z-Bee-Duo#4]
Greetings,
I had a CC2531 coordinator with 40+ devices and all used to work properly.
One day I decided to switch to a more powerful coordinator and I bought this `Z-Bee-Duo` from Tindie (a couple of weeks ago).

I flashed it to work with z2m based on the information provided here and on z2m website.
After two three times of restarting z2m, rebooting host etc, it started working without any need to re-pair my devices.
But then I noticed the network doesn't work properly (even main powered devices). 
On top of the general occasional issues, a few Aqara devices started to act stranagely. Even after re-pairing, they work for half an hour, and then they stop refreshing and never get connected back to the network. 
I had recently added 6 smart plugs (and thought they might be the problem), so on my latest debugging, I turned them all off and even removed then from my network (on z2m ui). Then re-paired the problematic devices and verified their Lqi and they were all good (as always). They got connected directly to the coordinator (I got this information by looking at z2m Map in ui). But again after 20-30 minutes they don't work any more. I am a bit tired of the amount of time I am spending on this. Can you guys give me a help how to debug or find a way to fix the issue?
By the way, there is no wifi-zigbee interference issue (as wifi is forced to use another band; also checked neighbours' wifi with wifi-analyzer). Also I already used a cable to attenuate potentially usb3 inteference.

Home Assistant: 2021.9.5 on Rpi4
Zigbee2Mqtt: 1.21.2-1
Coordinator: Z-Bee-Duo
Repeaters: Sonoff zbmini  x12 pcs around the house (they are actually wall switch with repeater capability)
End points: Aqara sensors, Sonoff sensors and buttons, Ikea remote

Any help would be appreciated.

**Comment by Gio-dot** [comment]
> Greetings, I had a CC2531 coordinator with 40+ devices and all used to work properly. One day I decided to switch to a more powerful coordinator and I bought this `Z-Bee-Duo` from Tindie (a couple of weeks ago).
> 
> I flashed it to work with z2m based on the information provided here and on z2m website. After two three times of restarting z2m, rebooting host etc, it started working without any need to re-pair my devices. But then I noticed the network doesn't work properly (even main powered devices). On top of the general occasional issues, a few Aqara devices started to act stranagely. Even after re-pairing, they work for half an hour, and then they stop refreshing and never get connected back to the network. I had recently added 6 smart plugs (and thought they might be the problem), so on my latest debugging, I turned them all off and even removed then from my network (on z2m ui). Then re-paired the problematic devices and verified their Lqi and they were all good (as always). They got connected directly to the coordinator (I got this information by looking at z2m Map in ui). But again after 20-30 minutes they don't work any more. I am a bit tired of the amount of time I am spending on this. Can you guys give me a help how to debug or find a way to fix the issue? By the way, there is no wifi-zigbee interference issue (as wifi is forced to use another band; also checked neighbours' wifi with wifi-analyzer). Also I already used a cable to attenuate potentially usb3 inteference.
> 
> Home Assistant: 2021.9.5 on Rpi4 Zigbee2Mqtt: 1.21.2-1 Coordinator: Z-Bee-Duo Repeaters: Sonoff zbmini x12 pcs around the house (they are actually wall switch with repeater capability) End points: Aqara sensors, Sonoff sensors and buttons, Ikea remote
> 
> Any help would be appreciated.

Hi, some question :.
1. Can you give me your order number (i want to check your stick version) ? 
2. Why did you flash the stick? It is shipped already flashed and ready to use.
3. Which firmware did you flash?

**Comment by Gio-dot** [comment]
Two suggestions:
1. Do not use the option to disable leds in z2m settings: it is not working yet and ca cause issues.
2. You should use this firmware:
https://github.com/egony/cc2652p_E72-2G4M20S1E/blob/master/firmware/coordinator/CC2652P_E72_20210319.zip
Latest Koenkk version give some issue to me.

**Comment by manunited10** [comment]
1. Disable LED id not activated.
2. I will reflash the firmware on the weekedn and report back. 
3.  This means I have to `reboot the house`, lol... I try my best.

**Comment by Gio-dot** [comment]
> Hi, So I flashed the firmware with the above firmware and also turned off/on all the routers at once. Nothing changed (actually one more aqara device dropped out!). I re-paired the probelmatic ones and they just stay connected for less than an hour. Do you have any other debugging solutions? By the way, one thing that I noticed is, by using this new firmware, some devices that are `directly` connected to the coordinator show Lqi = 0 in the `Map` tab of zigbee2mqtt ui (but not in the device tab).
Latest Z-stack firmwares solves issues with aqara devices. Please use this firmware: 
https://github.com/Koenkk/Z-Stack-firmware/blob/develop/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_other_coordinator_20211217.zip
