### ISSUE TITLE
Firmware update issue

### ISSUE THREAD

**Issue by jipema** [Gio-dot/Z-Bee-Duo#9]
Hi,
I was using this great little thing (on wifi) for about a year now, without any issue.
It was advised to update zigbee controller firmware to use a new device I've added to my network, so did I.
I followed the instructions (rev C, ebyte), and it seemed to work fine: no error message and command ending with "Verified (match 0x....)".

Unfortunately, after rebooting, my zigbee network is down, it seems like no new state can be published.
Is there something I need to re-configure, maybe on the esplink side?

**Comment by jipema** [comment]
I should add some precisions:
- no more red/green light blinking, only blue
- zigbee2mqtt logs mention some issues (might not be relevant though): 
`cont-init: info: running /etc/cont-init.d/socat.sh
[07:55:09] INFO: Socat not enabled, marking service as down
cont-init: info: /etc/cont-init.d/socat.sh exited 0`

**Comment by gio-dot** [comment]
Did you pick the right firmware version for ebyte chip?

**Comment by gio-dot** [comment]
Please look here:
 https://gio-dot.github.io/Z-Bee-Duo/

**Comment by gio-dot** [comment]
In the firmware update section.

**Comment by jipema** [comment]
I did exactly that, with the right firmware (chip is ebyte, firmware with the "other" tag in the filename). I even tried to downgrade to an older version without noticing any change (as it went through fine, I guess I can confirm the dongle is not bricked).

After more investigation, I noticed that the controller actually works, but only for getting state, not setting state: my remotes and miscellaneous sensors work just as fine as before the update, but it fails when trying to turn on a light for example.
Same behaviour both on usb and wifi.
Any clue?

**Comment by gio-dot** [comment]
Do you have some zigbee router in your network (powered switches, lamps, plugs etc) ?  In this case power cycle (off then on after some second) all of them (you can power off general main switch of your house).

**Comment by jipema** [comment]
Grazie mille Giovanni!
It definitely solved the problem! How did I not think of trying the good old 'reboot your computer' solution?

But now I'm curious, any idea what happened? How come the 'get state' worked but not the 'set state', and rebooting fixed it? Some request signature thing? Which would mean reading rights are not secured?
